### ISSUE TITLE
canno update from 0.19 

### ISSUE THREAD

**Issue by rasasak** [gschmidl/hassio-spoolman#6]
Error after click on UPDATE

can't install ghcr.io/donkie/spoolman:0.2: 500 Server Error for http+docker://localhost/v1.45/images/create?tag=0.2&fromImage=ghcr.io%2Fdonkie%2Fspoolman&platform=linux%2Famd64: Internal Server Error ("manifest unknown")

**Comment by gschmidl** [comment]
Fixed yesterday - you may have to update add-on sources to see it (should say 0.20.0 is available):

![image](https://github.com/user-attachments/assets/58694caa-563b-4be3-ae25-8b88c88588d2)
